---
# tasks file for postgres

- name: copy systmd unit file
  template: src=postgres.service.j2 dest=/etc/systemd/system/postgres.service mode=0755

- name:  Make sure a service is running
  systemd: 
    state: restarted 
    name: postgres
    enabled: yes
